Merging numpy/scipy/scikit-learn dependencies

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,9 +1,33 @@
 #!/usr/bin/env bash
 
-# Usage:
+# This script serves as the
+# [**Python Buildpack**](https://github.com/heroku/heroku-buildpack-python)
+# compiler.
+#
+# A [buildpack](http://devcenter.heroku.com/articles/buildpacks) is an
+# adapter between a Python application and Heroku's runtime.
+#
+# You can intreract with the Heroku API directly with [heroku.py](https://github.com/heroku/heroku.py/).
+#
+# See also: [Release history](/changelog.html), [Detection](/detect.html).
+#
+# ## Usage
+# Compiling an app into a slug is simple:
 #
 #     $ bin/compile <build-dir> <cache-dir>
 
+
+# ## Assumptions
+#
+# This buildpack makes the following assumptions:
+#
+# - The desired Python VM is available on the base system.
+# - Library dependencies are available on the base system.
+# - Django applications should not require any platform-specific configuration.
+
+# <hr />
+
+# ## Context
 
 # Fail fast and fail hard.
 set -eo pipefail
@@ -17,55 +41,60 @@ ROOT_DIR=$(dirname $BIN_DIR)
 BUILD_DIR=$1
 CACHE_DIR=$2
 
+# The detected application type (`Python`|`Python/Django`).
+NAME=$($BIN_DIR/detect $BUILD_DIR)
+
+# Where to store the Pip download cache.
 CACHED_DIRS=".heroku"
+PIP_DOWNLOAD_CACHE=${PIP_DOWNLOAD_CACHE:-$CACHE_DIR/pip_downloads}
 
 # Static configurations for virtualenv caches.
-VIRTUALENV_LOC=".heroku/venv"
-LEGACY_TRIGGER="lib/python2.7"
-PROFILE_PATH="$BUILD_DIR/.profile.d/python.sh"
+LEGACY_VIRTUALENV_LOC="."
+MODERN_VIRTUALENV_LOC=".heroku/venv"
+LEGACY_VIRTUALENV_DIRS="bin include lib"
+LEGACY_VIRTUALENV_TRIGGER="lib/python2.7"
+
 
 # Python version. This will be used in the future to specify custom Pythons.
-DEFAULT_PYTHON_VERSION="python-2.7.4"
-PYTHON_EXE="/app/.heroku/python/bin/python"
-PIP_VERSION="1.3.1"
-DISTRIBUTE_VERSION="0.6.36"
+PYTHON_VERSION="2.7.2"
+PYTHON_EXE="python2.7"
 
 # Sanitizing environment variables.
-unset GIT_DIR PYTHONHOME PYTHONPATH LD_LIBRARY_PATH LIBRARY_PATH
+unset GIT_DIR
+unset PYTHON_HOME
+unset PYTHONPATH
 
 # We'll need to send these statics to other scripts we `source`.
-export BUILD_DIR CACHE_DIR BIN_DIR PROFILE_PATH
+export PIP_DOWNLOAD_CACHE
+export BUILD_DIR
 
 # Syntax sugar.
-source $BIN_DIR/utils
+indent() {
+  RE="s/^/       /"
+  [ $(uname) == "Darwin" ] && sed -l "$RE" || sed -u "$RE"
+}
 
-# Directory Hacks for path consistiency.
-APP_DIR='/app'
-TMP_APP_DIR=$CACHE_DIR/tmp_app_dir
+function virtualenv (){
+  python "$ROOT_DIR/vendor/virtualenv-1.7/virtualenv.py" "$@"
+}
 
-# Copy Anvil app dir to temporary storage...
-mkdir -p $TMP_APP_DIR
-deep-mv $APP_DIR $TMP_APP_DIR
+function puts-step (){
+  echo "-----> $@"
+}
 
-# Copy Application code in.
-deep-mv $BUILD_DIR $APP_DIR
+function puts-warn (){
+  echo " !     $@"
+}
 
-# Set new context.
-ORIG_BUILD_DIR=$BUILD_DIR
-BUILD_DIR=$APP_DIR
-
-# Prepend proper path buildpack use.
-export PATH=$BUILD_DIR/.heroku/python/bin:$PATH
-export PYTHONUNBUFFERED=1
-export LANG=en_US.UTF-8
-export LIBRARY_PATH=/app/.heroku/vendor/lib
-export LD_LIBRARY_PATH=/app/.heroku/vendor/lib
+# ## Build Time
+#
 
 # Switch to the repo's context.
 cd $BUILD_DIR
 
-# Experimental pre_compile hook.
-source $BIN_DIR/steps/hooks/pre_compile
+# ### Sanity Checks
+#
+# Just a little peace of mind.
 
 # If no requirements given, assume `setup.py develop`.
 if [ ! -f requirements.txt ]; then
@@ -73,123 +102,118 @@ if [ ! -f requirements.txt ]; then
   echo "-e ." > requirements.txt
 fi
 
-# If no runtime given, assume default version.
-if [ ! -f runtime.txt ]; then
-  puts-step "No runtime.txt provided; assuming $DEFAULT_PYTHON_VERSION."
-  echo $DEFAULT_PYTHON_VERSION > runtime.txt
-fi
-
 # ### The Cache
 mkdir -p $CACHE_DIR
 
-# Purge "old-style" virtualenvs.
-[ -d $CACHE_DIR/$LEGACY_TRIGGER ] && rm -fr $CACHE_DIR/.heroku/bin $CACHE_DIR/.heroku/lib $CACHE_DIR/.heroku/include
-[ -d $CACHE_DIR/$VIRTUALENV_LOC ] && rm -fr $CACHE_DIR/.heroku/venv $CACHE_DIR/.heroku/src
+# Create set-aside `.heroku` folder.
+mkdir -p .heroku
+
+# Nice defaults.
+LEGACY_VIRTUALENV=false
+VIRTUALENV_LOC=$MODERN_VIRTUALENV_LOC
+
+# Support "old-style" virtualenvs.
+if [ -d $CACHE_DIR/$LEGACY_VIRTUALENV_TRIGGER ]; then
+  LEGACY_VIRTUALENV=true
+  VIRTUALENV_LOC=$LEGACY_VIRTUALENV_LOC
+  CACHED_DIRS=$LEGACY_VIRTUALENV_DIRS
+
+  # Warn for a checked-in virtualenv.
+  if [ -d "lib" ] || [ -d "bin" ]; then
+    puts-warn "You have a virtualenv checked in. You should ignore the appropriate paths in your repo. See http://devcenter.heroku.com/articles/gitignore for more info.";
+  fi
+
+  # Reject a conflicting checked-in virtualenv.
+  if [ -f "lib/python2.7" ]; then
+    puts-warn "Checked-in virtualenv conflict."
+    exit 1;
+  fi
+fi
 
 # Restore old artifacts from the cache.
 for dir in $CACHED_DIRS; do
   cp -R $CACHE_DIR/$dir . &> /dev/null || true
 done
 
+
+# ### Virtualenv Setup
+#
+
+# Create the virtualenv. Rebuild if corrupt.
+# TODO: Bootstrap a bottled Python VM...
+
 set +e
-# Create set-aside `.heroku` folder.
-mkdir .heroku &> /dev/null
-set -e
+puts-step "Preparing Python interpreter ($PYTHON_VERSION)"
+puts-step "Creating Virtualenv version $(virtualenv --version)"
 
-mkdir -p $(dirname $PROFILE_PATH)
+# Try to create the virtualenv.
+OUT=$(virtualenv --python $PYTHON_EXE --distribute --never-download --prompt='(venv) ' $VIRTUALENV_LOC 2>&1)
 
-set +e
-PYTHON_VERSION=$(cat runtime.txt)
-
-# Install Python.
-if [ -f .heroku/python-version ]; then
-  if [ ! $(cat .heroku/python-version) = $PYTHON_VERSION ]; then
-    puts-step "Found $(cat .heroku/python-version), removing."
-    rm -fr .heroku/python
-  else
-    SKIP_INSTALL=1
-  fi
-fi
-
-
-if [ ! "$SKIP_INSTALL" ]; then
-  puts-step "Preparing Python runtime ($PYTHON_VERSION)"
-  curl http://envy-versions.s3.amazonaws.com/$PYTHON_VERSION.tar.bz2 -s | tar jx &> /dev/null
-  if [[ $? != 0 ]] ; then
-    puts-warn "Requested runtime ($PYTHON_VERSION) was not found."
-    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
-    exit 1
-  fi
-  mv python .heroku/python
-
-  # Record for future reference.
-  echo $PYTHON_VERSION > .heroku/python-version
-  FRESH_PYTHON=true
-
-  hash -r
-else
-  puts-step "Using Python runtime ($PYTHON_VERSION)"
-fi
-
-# If Pip isn't up to date:
-if [ "$FRESH_PYTHON" ] || [[ ! $(pip --version) == *$PIP_VERSION* ]]; then
-  WORKING_DIR=$(pwd)
-
-  # Prepare it for the real world
-  puts-step "Installing Distribute ($DISTRIBUTE_VERSION)"
-  cd $ROOT_DIR/vendor/distribute-$DISTRIBUTE_VERSION/
-  python setup.py install &> /dev/null
-  cd $WORKING_DIR
-
-  puts-step "Installing Pip ($PIP_VERSION)"
-  cd $ROOT_DIR/vendor/pip-$PIP_VERSION/
-  python setup.py install &> /dev/null
-  cd $WORKING_DIR
-fi
+# If there's an error, purge and recreate.
+[ $? -ne 0 ] && {
+  puts-warn "Virtualenv corrupt, rebuilding."
+  for dir in $VIRTUALENV_DIRS; do
+    rm -fr $dir &> /dev/null || true
+  done
+  OUT=$(virtualenv --python $PYTHON_EXE --distribute --never-download  --prompt='(venv) ' $VIRTUALENV_LOC )
+}
+echo "$OUT" | indent
 
 set -e
-hash -r
 
 # Pylibmc support.
 # See [`bin/steps/pylibmc`](pylibmc.html).
 source $BIN_DIR/steps/pylibmc
 
+# Numpy/scipy support
+source $BIN_DIR/steps/npscipy
+
+# Scikit-Learn
+source $BIN_DIR/steps/scikit-learn
+
+
+# Activate the Virtualenv.
+puts-step "Activating virtualenv"
+source $VIRTUALENV_LOC/bin/activate
+
 # Install Mercurial if it appears to be required.
 if (grep -Fiq "hg+" requirements.txt) then
-  /app/.heroku/python/bin/pip install --use-mirrors mercurial | cleanup | indent
+  pip install --use-mirrors mercurial | indent
 fi
 
 # Install dependencies with Pip.
-puts-step "Installing dependencies using Pip ($PIP_VERSION)"
-/app/.heroku/python/bin/pip install --use-mirrors -r requirements.txt --exists-action=w --src=./.heroku/src | cleanup | indent
+puts-step "Installing dependencies using Pip version $(pip --version | awk '{print $2}')"
+pip install --use-mirrors -r requirements.txt --src ./.heroku/src | indent
 
-# Django collectstatic support.
-source $BIN_DIR/steps/collectstatic
+# Do additional application hackery if applications appears to be a Django app.
+# Optionally, disable all Django-specific changes with `DISABLE_INJECTION` env.
+#
+# See [`bin/steps/django`](django.html).
+
+if [ "$NAME" = "Python/Django" ] && ! [ "$DISABLE_INJECTION" ]; then
+  source $BIN_DIR/steps/django
+fi
+
+# Make Virtualenv's paths relative for portability.
+set +e
+OUT=$(virtualenv --python $PYTHON_EXE  --relocatable $VIRTUALENV_LOC)
+[ $? -ne 0 ] && {
+  puts-warn "Error making virtualenv relocatable"
+  echo "$OUT" | indent
+  exit 1
+}
+set -e
 
 # ### Finalize
 #
 
 # Store new artifacts in cache.
 for dir in $CACHED_DIRS; do
+
   rm -rf $CACHE_DIR/$dir
   cp -R $dir $CACHE_DIR/
 done
 
-# Set context environment variables.
-set-env PATH '$HOME/.heroku/python/bin:$PATH'
-set-env PYTHONUNBUFFERED true
-set-env PYTHONHOME /app/.heroku/python
-set-default-env LIBRARY_PATH /app/.heroku/vendor/lib
-set-default-env LD_LIBRARY_PATH /app/.heroku/vendor/lib
-set-default-env LANG en_US.UTF-8
-set-default-env PYTHONHASHSEED random
-set-default-env PYTHONPATH /app/
-
-
-# Experimental post_compile hook.
-source $BIN_DIR/steps/hooks/post_compile
-
 # ### Fin.
 
-deep-mv $BUILD_DIR $ORIG_BUILD_DIR
-deep-mv $TMP_APP_DIR $APP_DIR
+# <a href="http://github.com/heroku/heroku-buildpack-python"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://d3nwyuy0nl342s.cloudfront.net/img/7afbc8b248c68eb468279e8c17986ad46549fb71/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub"></a>
